@startuml

title Activity Diagram\nMilitary Combat

' Military Combat Segment
' Written by Samuel Foster
' Parents: /Turn/Military-Combat-Segment
' Children: 

(*) --> "Select Leader\n<i>Attacker" 
	--> "Select Leader\n<i>Defender"
	--> "Resolve Military Combat"
	--> (*)
@enduml