@startuml

title Activity Diagram\nStarsystem Player Turn

' Starsystem Player Turn
' Written by Samuel Foster
' Parents: /Turn/Starsystem-Game-Turn
' Children: /Turn/Operations-Phase /Turn/Search-Phase /Turn/Mission-Phase

(*) --> "<b>Operations Phase" as OP

OP --> "<b>Search Phase\n<i>Non-Phasing" as SP

SP --> "<b>Mission Phase" as MP

MP --> (*)
@enduml